version: '3.8'

networks:
  app-tier:
    driver: bridge

# Declare named volumes for persistence
volumes:
  zookeeper_data:
  kafka_data:

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - app-tier
    # Persist ZK data so that state survives container restarts
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.9
    ports:
      - 9094:9094
    environment:
      # unique broker ID
      - KAFKA_CFG_NODE_ID=0
      # connect to ZooKeeper for metadata
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # internal & external listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - app-tier
    # Persist Kafka’s log/data dir so topics & messages survive restarts
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - app-tier
